
# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing - force directive ensure all routes go through index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Make sure sitemap files are served correctly with proper content type
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/sitemap-index.xml"
  [headers.values]
    Content-Type = "application/xml"

# Assurez-vous que les assets sont correctement mis en cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ajouter des en-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Fix for SPA router - ensure direct deep links work
[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/mentions-legales/*"
  to = "/index.html"
  status = 200
