
# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Make sure sitemap files are served correctly with proper content type
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "all"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "all"

[[headers]]
  for = "/sitemap-index.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "all"

# Ensure all routes are allowed for crawling
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"
