
# Netlify configuration file optimisée pour le SEO
[build]
  publish = "dist"
  command = "npm run build"

# Configuration avancée pour servir du contenu statique aux robots et SPA aux humains
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*facebook*", "*twitter*"]}

[[redirects]]
  from = "/blog"
  to = "/blog/index.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*facebook*", "*twitter*"]}

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*facebook*", "*twitter*"]}

[[redirects]]
  from = "/mentions-legales"
  to = "/mentions-legales.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*facebook*", "*twitter*"]}

[[redirects]]
  from = "/politique-confidentialite"
  to = "/politique-confidentialite.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*facebook*", "*twitter*"]}

[[redirects]]
  from = "/conditions-utilisation"
  to = "/conditions-utilisation.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*facebook*", "*twitter*"]}

[[redirects]]
  from = "/politique-cookies"
  to = "/politique-cookies.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*facebook*", "*twitter*"]}

# Fallback SPA pour les utilisateurs humains
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers pour les fichiers XML (sitemaps)
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Robots-Tag = "index, follow"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sitemap-index.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Robots-Tag = "index, follow"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sitemap-content.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Robots-Tag = "index, follow"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"

# Headers pour les pages statiques HTML (pour les robots)
[[headers]]
  for = "/*.html"
  [headers.values]
    X-Robots-Tag = "index, follow, max-image-preview:large"
    Cache-Control = "public, max-age=3600"

# Headers spéciaux pour améliorer le SEO
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers pour les images
[[headers]]
  for = "/lovable-uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Robots-Tag = "index, follow"

# Headers pour les assets JS/CSS
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
