
# Netlify configuration file optimisée pour le SEO
[build]
  publish = "dist"
  command = "npm run build"

# Redirections simplifiées et optimisées pour les robots
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*Google*", "*Bing*"]}

[[redirects]]
  from = "/blog"
  to = "/blog/index.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*Google*", "*Bing*"]}

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*Google*", "*Bing*"]}

[[redirects]]
  from = "/mentions-legales"
  to = "/mentions-legales.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*Google*", "*Bing*"]}

[[redirects]]
  from = "/politique-confidentialite"
  to = "/politique-confidentialite.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*Google*", "*Bing*"]}

[[redirects]]
  from = "/conditions-utilisation"
  to = "/conditions-utilisation.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*Google*", "*Bing*"]}

[[redirects]]
  from = "/politique-cookies"
  to = "/politique-cookies.html"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawl*", "*spider*", "*Google*", "*Bing*"]}

# Redirections pour forcer l'indexation (nouveaux sitemaps)
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-v2-index.xml"
  status = 301

[[redirects]]
  from = "/sitemaps.xml"
  to = "/sitemap-v2-index.xml"
  status = 301

# Fallback SPA pour les utilisateurs humains
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers simplifiés et optimisés
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Robots-Tag = "index, follow"
    Cache-Control = "public, max-age=1800"

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Robots-Tag = "index, follow, max-image-preview:large"
    Cache-Control = "public, max-age=1800"
