
# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure sitemap files are served correctly with proper content type
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "index, follow"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/sitemap-index.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "index, follow"
    Access-Control-Allow-Origin = "*"
