
# Netlify configuration file optimisée pour le SEO
[build]
  publish = "dist"
  command = "npm run build"

# Redirections sitemaps
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-v2-index.xml"
  status = 301

[[redirects]]
  from = "/sitemaps.xml"
  to = "/sitemap-v2-index.xml"
  status = 301

# IMPORTANT: Les robots reçoivent les HTML statiques via les règles ci-dessous
# Googlebot et autres crawlers - redirection vers le dossier static-seo
[[redirects]]
  from = "/blog/*"
  to = "/static-seo/blog/:splat.html"
  status = 200
  conditions = {User-Agent = ["Googlebot", "Googlebot-Image", "Googlebot-News", "Googlebot-Video", "AdsBot-Google", "Bingbot", "Slurp", "DuckDuckBot", "Baiduspider", "YandexBot", "Sogou", "Exabot", "facebot", "facebookexternalhit", "ia_archiver"]}

[[redirects]]
  from = "/mentions-legales"
  to = "/static-seo/mentions-legales.html"
  status = 200
  conditions = {User-Agent = ["Googlebot", "Googlebot-Image", "Googlebot-News", "Googlebot-Video", "AdsBot-Google", "Bingbot", "Slurp", "DuckDuckBot", "Baiduspider", "YandexBot", "Sogou", "Exabot", "facebot", "facebookexternalhit", "ia_archiver"]}

[[redirects]]
  from = "/politique-confidentialite"
  to = "/static-seo/politique-confidentialite.html"
  status = 200
  conditions = {User-Agent = ["Googlebot", "Googlebot-Image", "Googlebot-News", "Googlebot-Video", "AdsBot-Google", "Bingbot", "Slurp", "DuckDuckBot", "Baiduspider", "YandexBot", "Sogou", "Exabot", "facebot", "facebookexternalhit", "ia_archiver"]}

[[redirects]]
  from = "/conditions-utilisation"
  to = "/static-seo/conditions-utilisation.html"
  status = 200
  conditions = {User-Agent = ["Googlebot", "Googlebot-Image", "Googlebot-News", "Googlebot-Video", "AdsBot-Google", "Bingbot", "Slurp", "DuckDuckBot", "Baiduspider", "YandexBot", "Sogou", "Exabot", "facebot", "facebookexternalhit", "ia_archiver"]}

[[redirects]]
  from = "/politique-cookies"
  to = "/static-seo/politique-cookies.html"
  status = 200
  conditions = {User-Agent = ["Googlebot", "Googlebot-Image", "Googlebot-News", "Googlebot-Video", "AdsBot-Google", "Bingbot", "Slurp", "DuckDuckBot", "Baiduspider", "YandexBot", "Sogou", "Exabot", "facebot", "facebookexternalhit", "ia_archiver"]}

# Fallback SPA React pour TOUS les utilisateurs normaux (DOIT être en dernier)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers simplifiés et optimisés
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Robots-Tag = "index, follow"
    Cache-Control = "public, max-age=1800"

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Robots-Tag = "index, follow, max-image-preview:large"
    Cache-Control = "public, max-age=1800"
