
# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Make sure sitemap files are served correctly with proper content type
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/sitemap-index.xml"
  [headers.values]
    Content-Type = "application/xml"

# Assurez-vous que les assets sont correctement mis en cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
